development: 
 adapter: postgresql  
 encoding: utf8 
 database: Eapp
 username: postgres  
 password: hanibal
 host: localhost

 production:  
 adapter: postgresql  
 encoding: utf8  
 database: Eapp 
 username: postgres  
 password: hanibal 
 host: localhost